FROM tensorflow/tensorflow:latest-gpu-jupyter
LABEL maintainer: @wolusien
# USER root
# RUN conda install --yes --name tf_dev pandas
# RUN ["bash", "-c", "source activate tf_dev && pip install bokeh"]
RUN ["bash", "-c", "pip install pandas"]
